matrix:

  include:
    - language: go
      go: 1.13.x
      dist: bionic
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
      cache:
        apt: true
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
      after_success:
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-pro -repotoken $COVERALLS_TOKEN

      before_install:
        - curl https://glide.sh/get | sh
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.20.0
        # todo cache apt package
        # - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install g++-6 gcc-6
        - export GO111MODULE=on
        - export GOPRIVATE=github.com/coinexchain/*
        - export GOROOT=$(go env GOROOT)
        - export CXX="g++-6" CC="gcc-6"
        - export PATH=$PATH:$HOME/gopath/bin

      install:
        - cd -
        - go mod tidy
        - go mod vendor
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls

      script:
        - RUN_IN_TRAVIS=true ./scripts/check.sh

notifications:
  email:
    on_success: change
    on_failure: always
